import {UserData, UserRoleType} from 'models';
import {API_URL} from 'react-native-dotenv';

const AppConfig = {
  baseUrl: API_URL,
  maximumFileSize: 100000000,
  showScrollMoreOffset: 275,
  timeoutCloseBottomSheet: 400,
  directCommunityId: 'b796712f-eea4-4ba1-abc6-ca76e9af24bc',
};

export const whiteListRefreshTokenApis = [
  'get-initial',
  'post-user/refresh',
  'post-user/address',
  'post-user',
];

export const ignoreMessageErrorApis = [
  'delete-user/device',
  'post-user/refresh',
];

export const emojiDefault = [
  {
    name: 'HEAVY BLACK HEART',
    unified: '2764-FE0F',
    non_qualified: '2764',
    docomo: 'E6EC',
    au: 'E595',
    softbank: 'E022',
    google: 'FEB0C',
    image: '2764-fe0f.png',
    sheet_x: 56,
    sheet_y: 32,
    short_name: 'heart',
    short_names: ['heart'],
    text: '<3',
    texts: ['<3'],
    category: 'Smileys & Emotion',
    subcategory: 'emotion',
    sort_order: 129,
    added_in: '0.6',
    has_img_apple: true,
    has_img_google: true,
    has_img_twitter: true,
    has_img_facebook: true,
    type: 'emoji',
    count: 1,
    timestamp: 10,
  },
  {
    name: 'FACE WITH TEARS OF JOY',
    unified: '1F602',
    non_qualified: null,
    docomo: 'E72A',
    au: 'EB64',
    softbank: 'E412',
    google: 'FE334',
    image: '1f602.png',
    sheet_x: 30,
    sheet_y: 34,
    short_name: 'joy',
    short_names: ['joy'],
    text: null,
    texts: null,
    category: 'Smileys & Emotion',
    subcategory: 'face-smiling',
    sort_order: 8,
    added_in: '0.6',
    has_img_apple: true,
    has_img_google: true,
    has_img_twitter: true,
    has_img_facebook: true,
    type: 'emoji',
    count: 1,
    timestamp: 9,
  },
  {
    name: 'FIRE',
    unified: '1F525',
    non_qualified: null,
    docomo: null,
    au: 'E47B',
    softbank: 'E11D',
    google: 'FE4F6',
    image: '1f525.png',
    sheet_x: 28,
    sheet_y: 7,
    short_name: 'fire',
    short_names: ['fire'],
    text: null,
    texts: null,
    category: 'Travel & Places',
    subcategory: 'sky & weather',
    sort_order: 985,
    added_in: '0.6',
    has_img_apple: true,
    has_img_google: true,
    has_img_twitter: true,
    has_img_facebook: true,
    type: 'emoji',
    count: 1,
    timestamp: 8,
  },
  {
    name: 'SMILING FACE WITH HEART-SHAPED EYES',
    unified: '1F60D',
    non_qualified: null,
    docomo: 'E726',
    au: 'E5C4',
    softbank: 'E106',
    google: 'FE327',
    image: '1f60d.png',
    sheet_x: 30,
    sheet_y: 45,
    short_name: 'heart_eyes',
    short_names: ['heart_eyes'],
    text: null,
    texts: null,
    category: 'Smileys & Emotion',
    subcategory: 'face-affection',
    sort_order: 15,
    added_in: '0.6',
    has_img_apple: true,
    has_img_google: true,
    has_img_twitter: true,
    has_img_facebook: true,
    type: 'emoji',
    count: 1,
    timestamp: 7,
  },
  {
    name: 'EYES',
    unified: '1F440',
    non_qualified: null,
    docomo: 'E691',
    au: 'E5A4',
    softbank: 'E419',
    google: 'FE190',
    image: '1f440.png',
    sheet_x: 12,
    sheet_y: 27,
    short_name: 'eyes',
    short_names: ['eyes'],
    text: null,
    texts: null,
    category: 'People & Body',
    subcategory: 'body-parts',
    sort_order: 199,
    added_in: '0.6',
    has_img_apple: true,
    has_img_google: true,
    has_img_twitter: true,
    has_img_facebook: true,
    type: 'emoji',
    count: 1,
    timestamp: 6,
  },
];

export const reportData = [
  'Spam',
  'Violence',
  'Pornography',
  'Child Abuse',
  'Copyright',
  'Illegal Drugs',
  'Personal Details',
  'Other',
];

export const UserRole: {
  Owner: UserRoleType;
  Admin: UserRoleType;
  Member: UserRoleType;
} = {
  Owner: 'owner',
  Admin: 'admin',
  Member: 'member',
};

export default AppConfig;

export const DeletedUser: UserData = {
  user_id: '',
  user_name: 'Deleted User',
  avatar_url: '',
};
